/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.ActivesessionResponseCompoundUser
import eZmaxApi.models.FieldEUserEzsignsendreminderfrequency

class ActivesessionResponseCompoundUserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActivesessionResponseCompoundUser
        //val modelInstance = ActivesessionResponseCompoundUser()

        // to test the property `pkiUserID` - The unique ID of the User
        should("test pkiUserID") {
            // uncomment below to test the property
            //modelInstance.pkiUserID shouldBe ("TODO")
        }

        // to test the property `fkiTimezoneID` - The unique ID of the Timezone
        should("test fkiTimezoneID") {
            // uncomment below to test the property
            //modelInstance.fkiTimezoneID shouldBe ("TODO")
        }

        // to test the property `sUserFirstname` - The first name of the user
        should("test sUserFirstname") {
            // uncomment below to test the property
            //modelInstance.sUserFirstname shouldBe ("TODO")
        }

        // to test the property `sUserLastname` - The last name of the user
        should("test sUserLastname") {
            // uncomment below to test the property
            //modelInstance.sUserLastname shouldBe ("TODO")
        }

        // to test the property `eUserEzsignsendreminderfrequency`
        should("test eUserEzsignsendreminderfrequency") {
            // uncomment below to test the property
            //modelInstance.eUserEzsignsendreminderfrequency shouldBe ("TODO")
        }

        // to test the property `iUserInterfacecolor` - The int32 representation of the interface color. For example, RGB color #39435B would be 3752795
        should("test iUserInterfacecolor") {
            // uncomment below to test the property
            //modelInstance.iUserInterfacecolor shouldBe ("TODO")
        }

        // to test the property `bUserInterfacedark` - Whether to use a dark mode interface
        should("test bUserInterfacedark") {
            // uncomment below to test the property
            //modelInstance.bUserInterfacedark shouldBe ("TODO")
        }

        // to test the property `iUserListresult` - The number of rows to return by default in lists
        should("test iUserListresult") {
            // uncomment below to test the property
            //modelInstance.iUserListresult shouldBe ("TODO")
        }

        // to test the property `sAvatarUrl` - The url of the picture used as avatar
        should("test sAvatarUrl") {
            // uncomment below to test the property
            //modelInstance.sAvatarUrl shouldBe ("TODO")
        }

        // to test the property `sEmailAddress` - The email address.
        should("test sEmailAddress") {
            // uncomment below to test the property
            //modelInstance.sEmailAddress shouldBe ("TODO")
        }

    }
}
