/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.ApikeyGenerateDelegatedCredentialsV1ResponseMPayload
import eZmaxApi.models.CustomApikey

class ApikeyGenerateDelegatedCredentialsV1ResponseMPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApikeyGenerateDelegatedCredentialsV1ResponseMPayload
        //val modelInstance = ApikeyGenerateDelegatedCredentialsV1ResponseMPayload()

        // to test the property `objApikey`
        should("test objApikey") {
            // uncomment below to test the property
            //modelInstance.objApikey shouldBe ("TODO")
        }

    }
}
