/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.AuthenticationexternalEditObjectV1Request
import eZmaxApi.models.AuthenticationexternalRequestCompound

class AuthenticationexternalEditObjectV1RequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthenticationexternalEditObjectV1Request
        //val modelInstance = AuthenticationexternalEditObjectV1Request()

        // to test the property `objAuthenticationexternal`
        should("test objAuthenticationexternal") {
            // uncomment below to test the property
            //modelInstance.objAuthenticationexternal shouldBe ("TODO")
        }

    }
}
