/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.CreditcardclientGetObjectV2Response
import eZmaxApi.models.CommonResponse
import eZmaxApi.models.CommonResponseObjDebug
import eZmaxApi.models.CommonResponseObjDebugPayload
import eZmaxApi.models.CreditcardclientGetObjectV2ResponseMPayload

class CreditcardclientGetObjectV2ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreditcardclientGetObjectV2Response
        //val modelInstance = CreditcardclientGetObjectV2Response()

        // to test the property `mPayload`
        should("test mPayload") {
            // uncomment below to test the property
            //modelInstance.mPayload shouldBe ("TODO")
        }

    }
}
