/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.CustomDnsrecordResponse

class CustomDnsrecordResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomDnsrecordResponse
        //val modelInstance = CustomDnsrecordResponse()

        // to test the property `eDnsrecordType` - The type of the Dnsrecord
        should("test eDnsrecordType") {
            // uncomment below to test the property
            //modelInstance.eDnsrecordType shouldBe ("TODO")
        }

        // to test the property `eDnsrecordValidation` - The validation of the Dnsrecord
        should("test eDnsrecordValidation") {
            // uncomment below to test the property
            //modelInstance.eDnsrecordValidation shouldBe ("TODO")
        }

        // to test the property `sDnsrecordName` - The name of the Dnsrecord
        should("test sDnsrecordName") {
            // uncomment below to test the property
            //modelInstance.sDnsrecordName shouldBe ("TODO")
        }

        // to test the property `bDnsrecordMustMatch` - Whether the Dnsrecord must match or not
        should("test bDnsrecordMustMatch") {
            // uncomment below to test the property
            //modelInstance.bDnsrecordMustMatch shouldBe ("TODO")
        }

        // to test the property `sDnsrecordValue` - The value of the Dnsrecord
        should("test sDnsrecordValue") {
            // uncomment below to test the property
            //modelInstance.sDnsrecordValue shouldBe ("TODO")
        }

        // to test the property `sDnsrecordExpectedvalue` - The expected value of the Dnsrecord
        should("test sDnsrecordExpectedvalue") {
            // uncomment below to test the property
            //modelInstance.sDnsrecordExpectedvalue shouldBe ("TODO")
        }

    }
}
