/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.DomainGetObjectV2ResponseMPayload
import eZmaxApi.models.DomainResponseCompound

class DomainGetObjectV2ResponseMPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DomainGetObjectV2ResponseMPayload
        //val modelInstance = DomainGetObjectV2ResponseMPayload()

        // to test the property `objDomain`
        should("test objDomain") {
            // uncomment below to test the property
            //modelInstance.objDomain shouldBe ("TODO")
        }

    }
}
