/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.EzsignfolderReorderV1Request

class EzsignfolderReorderV1RequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EzsignfolderReorderV1Request
        //val modelInstance = EzsignfolderReorderV1Request()

        // to test the property `aPkiEzsigndocumentID`
        should("test aPkiEzsigndocumentID") {
            // uncomment below to test the property
            //modelInstance.aPkiEzsigndocumentID shouldBe ("TODO")
        }

    }
}
