/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.EzsignformfieldResponseCompound
import eZmaxApi.models.EnumHorizontalalignment
import eZmaxApi.models.EzsignelementdependencyResponse
import eZmaxApi.models.EzsignformfieldResponse
import eZmaxApi.models.FieldEEzsignformfieldDependencyrequirement
import eZmaxApi.models.TextstylestaticResponseCompound

class EzsignformfieldResponseCompoundTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EzsignformfieldResponseCompound
        //val modelInstance = EzsignformfieldResponseCompound()

        // to test the property `aObjEzsignelementdependency`
        should("test aObjEzsignelementdependency") {
            // uncomment below to test the property
            //modelInstance.aObjEzsignelementdependency shouldBe ("TODO")
        }

    }
}
