/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.EzsignsignatureGetObjectV2ResponseMPayload
import eZmaxApi.models.EzsignsignatureResponseCompound

class EzsignsignatureGetObjectV2ResponseMPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EzsignsignatureGetObjectV2ResponseMPayload
        //val modelInstance = EzsignsignatureGetObjectV2ResponseMPayload()

        // to test the property `objEzsignsignature`
        should("test objEzsignsignature") {
            // uncomment below to test the property
            //modelInstance.objEzsignsignature shouldBe ("TODO")
        }

    }
}
