/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.EzsigndocumentGetActionableElementsV1ResponseMPayload
import eZmaxApi.models.EzsignformfieldgroupResponseCompound
import eZmaxApi.models.EzsignsignatureResponseCompound

class EzsigndocumentGetActionableElementsV1ResponseMPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EzsigndocumentGetActionableElementsV1ResponseMPayload
        //val modelInstance = EzsigndocumentGetActionableElementsV1ResponseMPayload()

        // to test the property `aObjEzsignsignature`
        should("test aObjEzsignsignature") {
            // uncomment below to test the property
            //modelInstance.aObjEzsignsignature shouldBe ("TODO")
        }

        // to test the property `aObjEzsignformfieldgroup`
        should("test aObjEzsignformfieldgroup") {
            // uncomment below to test the property
            //modelInstance.aObjEzsignformfieldgroup shouldBe ("TODO")
        }

    }
}
