/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.EzsigndocumentGetEzsignpagesV1ResponseMPayload
import eZmaxApi.models.EzsignpageResponseCompound

class EzsigndocumentGetEzsignpagesV1ResponseMPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EzsigndocumentGetEzsignpagesV1ResponseMPayload
        //val modelInstance = EzsigndocumentGetEzsignpagesV1ResponseMPayload()

        // to test the property `aObjEzsignpage`
        should("test aObjEzsignpage") {
            // uncomment below to test the property
            //modelInstance.aObjEzsignpage shouldBe ("TODO")
        }

    }
}
