/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.NotificationtestResponse
import eZmaxApi.models.MultilingualNotificationtestName

class NotificationtestResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationtestResponse
        //val modelInstance = NotificationtestResponse()

        // to test the property `pkiNotificationtestID` - The unique ID of the Notificationtest
        should("test pkiNotificationtestID") {
            // uncomment below to test the property
            //modelInstance.pkiNotificationtestID shouldBe ("TODO")
        }

        // to test the property `objNotificationtestName`
        should("test objNotificationtestName") {
            // uncomment below to test the property
            //modelInstance.objNotificationtestName shouldBe ("TODO")
        }

        // to test the property `fkiNotificationsubsectionID` - The unique ID of the Notificationsubsection
        should("test fkiNotificationsubsectionID") {
            // uncomment below to test the property
            //modelInstance.fkiNotificationsubsectionID shouldBe ("TODO")
        }

        // to test the property `sNotificationtestFunction` - The function name of the Notificationtest
        should("test sNotificationtestFunction") {
            // uncomment below to test the property
            //modelInstance.sNotificationtestFunction shouldBe ("TODO")
        }

        // to test the property `sNotificationtestNameX` - The name of the Notificationtest in the language of the requester
        should("test sNotificationtestNameX") {
            // uncomment below to test the property
            //modelInstance.sNotificationtestNameX shouldBe ("TODO")
        }

    }
}
