/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.PaymenttermGetListV1Response
import eZmaxApi.models.CommonResponseGetList
import eZmaxApi.models.CommonResponseObjDebug
import eZmaxApi.models.CommonResponseObjDebugPayloadGetList
import eZmaxApi.models.PaymenttermGetListV1ResponseMPayload

class PaymenttermGetListV1ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymenttermGetListV1Response
        //val modelInstance = PaymenttermGetListV1Response()

        // to test the property `mPayload`
        should("test mPayload") {
            // uncomment below to test the property
            //modelInstance.mPayload shouldBe ("TODO")
        }

    }
}
