/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.PermissionGetObjectV2Response
import eZmaxApi.models.CommonResponseObjDebug
import eZmaxApi.models.CommonResponseObjDebugPayload
import eZmaxApi.models.PermissionGetObjectV2ResponseMPayload

class PermissionGetObjectV2ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PermissionGetObjectV2Response
        //val modelInstance = PermissionGetObjectV2Response()

        // to test the property `objDebugPayload`
        should("test objDebugPayload") {
            // uncomment below to test the property
            //modelInstance.objDebugPayload shouldBe ("TODO")
        }

        // to test the property `mPayload`
        should("test mPayload") {
            // uncomment below to test the property
            //modelInstance.mPayload shouldBe ("TODO")
        }

        // to test the property `objDebug`
        should("test objDebug") {
            // uncomment below to test the property
            //modelInstance.objDebug shouldBe ("TODO")
        }

    }
}
