/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.PermissionResponse

class PermissionResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PermissionResponse
        //val modelInstance = PermissionResponse()

        // to test the property `pkiPermissionID` - The unique ID of the Permission
        should("test pkiPermissionID") {
            // uncomment below to test the property
            //modelInstance.pkiPermissionID shouldBe ("TODO")
        }

        // to test the property `fkiModulesectionID` - The unique ID of the Modulesection
        should("test fkiModulesectionID") {
            // uncomment below to test the property
            //modelInstance.fkiModulesectionID shouldBe ("TODO")
        }

        // to test the property `fkiUserID` - The unique ID of the User
        should("test fkiUserID") {
            // uncomment below to test the property
            //modelInstance.fkiUserID shouldBe ("TODO")
        }

        // to test the property `fkiApikeyID` - The unique ID of the Apikey
        should("test fkiApikeyID") {
            // uncomment below to test the property
            //modelInstance.fkiApikeyID shouldBe ("TODO")
        }

        // to test the property `fkiUsergroupID` - The unique ID of the Usergroup
        should("test fkiUsergroupID") {
            // uncomment below to test the property
            //modelInstance.fkiUsergroupID shouldBe ("TODO")
        }

        // to test the property `fkiCompanyID` - The unique ID of the Company
        should("test fkiCompanyID") {
            // uncomment below to test the property
            //modelInstance.fkiCompanyID shouldBe ("TODO")
        }

        // to test the property `sCompanyNameX` - The Name of the Company in the language of the requester
        should("test sCompanyNameX") {
            // uncomment below to test the property
            //modelInstance.sCompanyNameX shouldBe ("TODO")
        }

    }
}
