/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.ScimUserList
import eZmaxApi.models.ScimUser

class ScimUserListTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ScimUserList
        //val modelInstance = ScimUserList()

        // to test the property `totalResults`
        should("test totalResults") {
            // uncomment below to test the property
            //modelInstance.totalResults shouldBe ("TODO")
        }

        // to test the property `itemsPerPage`
        should("test itemsPerPage") {
            // uncomment below to test the property
            //modelInstance.itemsPerPage shouldBe ("TODO")
        }

        // to test the property `startIndex`
        should("test startIndex") {
            // uncomment below to test the property
            //modelInstance.startIndex shouldBe ("TODO")
        }

        // to test the property `schemas`
        should("test schemas") {
            // uncomment below to test the property
            //modelInstance.schemas shouldBe ("TODO")
        }

        // to test the property `resources`
        should("test resources") {
            // uncomment below to test the property
            //modelInstance.resources shouldBe ("TODO")
        }

    }
}
