/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.ScimEmail

class ScimEmailTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ScimEmail
        //val modelInstance = ScimEmail()

        // to test the property ``value`` - The email address.
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `primary`
        should("test primary") {
            // uncomment below to test the property
            //modelInstance.primary shouldBe ("TODO")
        }

    }
}
