/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.SupplyEditObjectV1Request
import eZmaxApi.models.SupplyRequestCompound

class SupplyEditObjectV1RequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SupplyEditObjectV1Request
        //val modelInstance = SupplyEditObjectV1Request()

        // to test the property `objSupply`
        should("test objSupply") {
            // uncomment below to test the property
            //modelInstance.objSupply shouldBe ("TODO")
        }

    }
}
