/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.UsergroupGetListV1ResponseMPayload
import eZmaxApi.models.CommonGetListV1ResponseMPayload
import eZmaxApi.models.UsergroupListElement

class UsergroupGetListV1ResponseMPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsergroupGetListV1ResponseMPayload
        //val modelInstance = UsergroupGetListV1ResponseMPayload()

        // to test the property `aObjUsergroup`
        should("test aObjUsergroup") {
            // uncomment below to test the property
            //modelInstance.aObjUsergroup shouldBe ("TODO")
        }

    }
}
