/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.models.UsergroupGetUsergroupmembershipsV1ResponseMPayload
import eZmaxApi.models.UsergroupmembershipResponseCompound

class UsergroupGetUsergroupmembershipsV1ResponseMPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsergroupGetUsergroupmembershipsV1ResponseMPayload
        //val modelInstance = UsergroupGetUsergroupmembershipsV1ResponseMPayload()

        // to test the property `aObjUsergroupmembership`
        should("test aObjUsergroupmembership") {
            // uncomment below to test the property
            //modelInstance.aObjUsergroupmembership shouldBe ("TODO")
        }

    }
}
