/**
* eZmax API Definition
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.0.37
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package eZmaxinc/eZmax-SDK-kotlin.models

import eZmaxinc/eZmax-SDK-kotlin.models.EzsigndocumentMinusRequest

import com.squareup.moshi.Json

/**
 * Request for the /1/object/ezsigndocument/editObject API Request
 * @param objEzsigndocument 
 */

data class UNUSEDMinusEzsigndocumentMinusEditObjectMinusV1MinusRequest (
    @Json(name = "objEzsigndocument")
    val objEzsigndocument: EzsigndocumentMinusRequest? = null
)

