/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.apis.ObjectEzsigntemplatesignatureApi
import eZmaxApi.models.CommonResponseError
import eZmaxApi.models.EzsigntemplatesignatureCreateObjectV1Request
import eZmaxApi.models.EzsigntemplatesignatureCreateObjectV1Response
import eZmaxApi.models.EzsigntemplatesignatureDeleteObjectV1Response
import eZmaxApi.models.EzsigntemplatesignatureEditObjectV1Request
import eZmaxApi.models.EzsigntemplatesignatureEditObjectV1Response
import eZmaxApi.models.EzsigntemplatesignatureGetObjectV2Response

class ObjectEzsigntemplatesignatureApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ObjectEzsigntemplatesignatureApi
        //val apiInstance = ObjectEzsigntemplatesignatureApi()

        // to test ezsigntemplatesignatureCreateObjectV1
        should("test ezsigntemplatesignatureCreateObjectV1") {
            // uncomment below to test ezsigntemplatesignatureCreateObjectV1
            //val ezsigntemplatesignatureCreateObjectV1Request : EzsigntemplatesignatureCreateObjectV1Request =  // EzsigntemplatesignatureCreateObjectV1Request | 
            //val result : EzsigntemplatesignatureCreateObjectV1Response = apiInstance.ezsigntemplatesignatureCreateObjectV1(ezsigntemplatesignatureCreateObjectV1Request)
            //result shouldBe ("TODO")
        }

        // to test ezsigntemplatesignatureDeleteObjectV1
        should("test ezsigntemplatesignatureDeleteObjectV1") {
            // uncomment below to test ezsigntemplatesignatureDeleteObjectV1
            //val pkiEzsigntemplatesignatureID : kotlin.Int = 56 // kotlin.Int | 
            //val result : EzsigntemplatesignatureDeleteObjectV1Response = apiInstance.ezsigntemplatesignatureDeleteObjectV1(pkiEzsigntemplatesignatureID)
            //result shouldBe ("TODO")
        }

        // to test ezsigntemplatesignatureEditObjectV1
        should("test ezsigntemplatesignatureEditObjectV1") {
            // uncomment below to test ezsigntemplatesignatureEditObjectV1
            //val pkiEzsigntemplatesignatureID : kotlin.Int = 56 // kotlin.Int | 
            //val ezsigntemplatesignatureEditObjectV1Request : EzsigntemplatesignatureEditObjectV1Request =  // EzsigntemplatesignatureEditObjectV1Request | 
            //val result : EzsigntemplatesignatureEditObjectV1Response = apiInstance.ezsigntemplatesignatureEditObjectV1(pkiEzsigntemplatesignatureID, ezsigntemplatesignatureEditObjectV1Request)
            //result shouldBe ("TODO")
        }

        // to test ezsigntemplatesignatureGetObjectV2
        should("test ezsigntemplatesignatureGetObjectV2") {
            // uncomment below to test ezsigntemplatesignatureGetObjectV2
            //val pkiEzsigntemplatesignatureID : kotlin.Int = 56 // kotlin.Int | 
            //val result : EzsigntemplatesignatureGetObjectV2Response = apiInstance.ezsigntemplatesignatureGetObjectV2(pkiEzsigntemplatesignatureID)
            //result shouldBe ("TODO")
        }

    }
}
