/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.apis.ObjectEzsignpageApi
import eZmaxApi.models.CommonResponse
import eZmaxApi.models.CommonResponseError

class ObjectEzsignpageApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ObjectEzsignpageApi
        //val apiInstance = ObjectEzsignpageApi()

        // to test ezsignpageConsultV1
        should("test ezsignpageConsultV1") {
            // uncomment below to test ezsignpageConsultV1
            //val pkiEzsignpageID : kotlin.Int = 56 // kotlin.Int | 
            //val body : kotlin.Any = Object // kotlin.Any | 
            //val result : CommonResponse = apiInstance.ezsignpageConsultV1(pkiEzsignpageID, body)
            //result shouldBe ("TODO")
        }

    }
}
