/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import eZmaxApi.apis.ObjectEzdoctemplatedocumentApi
import eZmaxApi.models.CommonResponse
import eZmaxApi.models.CommonResponseError
import eZmaxApi.models.EzdoctemplatedocumentCreateObjectV1Request
import eZmaxApi.models.EzdoctemplatedocumentCreateObjectV1Response
import eZmaxApi.models.EzdoctemplatedocumentEditObjectV1Request
import eZmaxApi.models.EzdoctemplatedocumentGetAutocompleteV2Response
import eZmaxApi.models.EzdoctemplatedocumentGetListV1Response
import eZmaxApi.models.EzdoctemplatedocumentGetObjectV2Response
import eZmaxApi.models.EzdoctemplatedocumentPatchObjectV1Request
import eZmaxApi.models.HeaderAcceptLanguage

class ObjectEzdoctemplatedocumentApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ObjectEzdoctemplatedocumentApi
        //val apiInstance = ObjectEzdoctemplatedocumentApi()

        // to test ezdoctemplatedocumentCreateObjectV1
        should("test ezdoctemplatedocumentCreateObjectV1") {
            // uncomment below to test ezdoctemplatedocumentCreateObjectV1
            //val ezdoctemplatedocumentCreateObjectV1Request : EzdoctemplatedocumentCreateObjectV1Request =  // EzdoctemplatedocumentCreateObjectV1Request | 
            //val result : EzdoctemplatedocumentCreateObjectV1Response = apiInstance.ezdoctemplatedocumentCreateObjectV1(ezdoctemplatedocumentCreateObjectV1Request)
            //result shouldBe ("TODO")
        }

        // to test ezdoctemplatedocumentDownloadV1
        should("test ezdoctemplatedocumentDownloadV1") {
            // uncomment below to test ezdoctemplatedocumentDownloadV1
            //val pkiEzdoctemplatedocumentID : kotlin.Int = 56 // kotlin.Int | 
            //apiInstance.ezdoctemplatedocumentDownloadV1(pkiEzdoctemplatedocumentID)
        }

        // to test ezdoctemplatedocumentEditObjectV1
        should("test ezdoctemplatedocumentEditObjectV1") {
            // uncomment below to test ezdoctemplatedocumentEditObjectV1
            //val pkiEzdoctemplatedocumentID : kotlin.Int = 56 // kotlin.Int | The unique ID of the Ezdoctemplatedocument
            //val ezdoctemplatedocumentEditObjectV1Request : EzdoctemplatedocumentEditObjectV1Request =  // EzdoctemplatedocumentEditObjectV1Request | 
            //val result : CommonResponse = apiInstance.ezdoctemplatedocumentEditObjectV1(pkiEzdoctemplatedocumentID, ezdoctemplatedocumentEditObjectV1Request)
            //result shouldBe ("TODO")
        }

        // to test ezdoctemplatedocumentGetAutocompleteV2
        should("test ezdoctemplatedocumentGetAutocompleteV2") {
            // uncomment below to test ezdoctemplatedocumentGetAutocompleteV2
            //val sSelector : kotlin.String = sSelector_example // kotlin.String | The type of Ezdoctemplatedocuments to return
            //val eType : kotlin.String = eType_example // kotlin.String | The type of Ezdoctemplatedocument
            //val fkiEzsignfoldertypeID : kotlin.String = fkiEzsignfoldertypeID_example // kotlin.String | Specify which fkiEzsignfoldertypeID we want to display. only used when eType = Ezsignfoldertype
            //val eFilterActive : kotlin.String = eFilterActive_example // kotlin.String | Specify which results we want to display.
            //val sQuery : kotlin.String = sQuery_example // kotlin.String | Allow to filter the returned results
            //val acceptLanguage : HeaderAcceptLanguage =  // HeaderAcceptLanguage | 
            //val result : EzdoctemplatedocumentGetAutocompleteV2Response = apiInstance.ezdoctemplatedocumentGetAutocompleteV2(sSelector, eType, fkiEzsignfoldertypeID, eFilterActive, sQuery, acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test ezdoctemplatedocumentGetListV1
        should("test ezdoctemplatedocumentGetListV1") {
            // uncomment below to test ezdoctemplatedocumentGetListV1
            //val eOrderBy : kotlin.String = eOrderBy_example // kotlin.String | Specify how you want the results to be sorted
            //val iRowMax : kotlin.Int = 56 // kotlin.Int | 
            //val iRowOffset : kotlin.Int = 56 // kotlin.Int | 
            //val acceptLanguage : HeaderAcceptLanguage =  // HeaderAcceptLanguage | 
            //val sFilter : kotlin.String = sFilter_example // kotlin.String | 
            //val result : EzdoctemplatedocumentGetListV1Response = apiInstance.ezdoctemplatedocumentGetListV1(eOrderBy, iRowMax, iRowOffset, acceptLanguage, sFilter)
            //result shouldBe ("TODO")
        }

        // to test ezdoctemplatedocumentGetObjectV2
        should("test ezdoctemplatedocumentGetObjectV2") {
            // uncomment below to test ezdoctemplatedocumentGetObjectV2
            //val pkiEzdoctemplatedocumentID : kotlin.Int = 56 // kotlin.Int | The unique ID of the Ezdoctemplatedocument
            //val result : EzdoctemplatedocumentGetObjectV2Response = apiInstance.ezdoctemplatedocumentGetObjectV2(pkiEzdoctemplatedocumentID)
            //result shouldBe ("TODO")
        }

        // to test ezdoctemplatedocumentPatchObjectV1
        should("test ezdoctemplatedocumentPatchObjectV1") {
            // uncomment below to test ezdoctemplatedocumentPatchObjectV1
            //val pkiEzdoctemplatedocumentID : kotlin.Int = 56 // kotlin.Int | The unique ID of the Ezdoctemplatedocument
            //val ezdoctemplatedocumentPatchObjectV1Request : EzdoctemplatedocumentPatchObjectV1Request =  // EzdoctemplatedocumentPatchObjectV1Request | 
            //val result : CommonResponse = apiInstance.ezdoctemplatedocumentPatchObjectV1(pkiEzdoctemplatedocumentID, ezdoctemplatedocumentPatchObjectV1Request)
            //result shouldBe ("TODO")
        }

    }
}
