/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import eZmaxApi.models.ActivesessionResponseCompound

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Payload for GET /1/object/activesession/getCurrent
 *
 * @param objActivesession 
 */


data class ActivesessionGetCurrentV2ResponseMPayload (

    @Json(name = "objActivesession")
    val objActivesession: ActivesessionResponseCompound

) {


}

