/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import eZmaxApi.models.ApikeyRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Request for PUT /1/object/apikey/{pkiApikeyID}
 *
 * @param objApikey An Apikey Object and children to create a complete structure
 */


data class ApikeyEditObjectV1Request (

    /* An Apikey Object and children to create a complete structure */
    @Json(name = "objApikey")
    val objApikey: ApikeyRequest

) {


}

