/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import eZmaxApi.models.AuthenticationexternalRequest
import eZmaxApi.models.FieldEAuthenticationexternalType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A Authenticationexternal Object and children
 *
 * @param sAuthenticationexternalDescription The description of the Authenticationexternal
 * @param eAuthenticationexternalType 
 * @param pkiAuthenticationexternalID The unique ID of the Authenticationexternal
 */


class AuthenticationexternalRequestCompound (

    /* The description of the Authenticationexternal */
    @Json(name = "sAuthenticationexternalDescription")
    override val sAuthenticationexternalDescription: kotlin.String,

    @Json(name = "eAuthenticationexternalType")
    override val eAuthenticationexternalType: FieldEAuthenticationexternalType,

    /* The unique ID of the Authenticationexternal */
    @Json(name = "pkiAuthenticationexternalID")
    override val pkiAuthenticationexternalID: kotlin.Int? = null

) : AuthenticationexternalRequest {


}

