/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import eZmaxApi.models.BillingentityinternalMinusRequestCompound

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Request for POST /1/object/billingentityinternal
 *
 * @param aObjBillingentityinternal 
 */


data class BillingentityinternalMinusCreateObjectMinusV1MinusRequest (

    @Json(name = "a_objBillingentityinternal")
    val aObjBillingentityinternal: kotlin.collections.List<BillingentityinternalMinusRequestCompound>

)

