/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A Brokertype AutocompleteElement Response
 *
 * @param pkiBrokertypeID The unique ID of the Brokertype
 * @param sBrokertypeNameX The name of the Brokertype in the language of the requester
 * @param bBrokertypeIsactive Whether the Brokertype is active or not
 */


data class BrokertypeAutocompleteElementResponse (

    /* The unique ID of the Brokertype */
    @Json(name = "pkiBrokertypeID")
    val pkiBrokertypeID: kotlin.Int,

    /* The name of the Brokertype in the language of the requester */
    @Json(name = "sBrokertypeNameX")
    val sBrokertypeNameX: kotlin.String,

    /* Whether the Brokertype is active or not */
    @Json(name = "bBrokertypeIsactive")
    val bBrokertypeIsactive: kotlin.Boolean

) {


}

