/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A Creditcardmerchant List Element
 *
 * @param pkiCreditcardmerchantID The unique ID of the Creditcardmerchant
 * @param fkiBankaccountID The unique ID of the Bankaccount
 * @param bCreditcardmerchantDenyvisa Whether if visa are denied
 * @param bCreditcardmerchantDenymastercard Whether if mastercard are denied
 * @param bCreditcardmerchantDenyamex Whether if amex are denied
 * @param bCreditcardmerchantIsactive Whether the creditcardmerchant is active or not
 * @param sCreditcardmerchantDescription The description of the Creditcardmerchant
 * @param sCreditcardmerchantStoreid The storeid of the Creditcardmerchant
 * @param fkiLanguageID The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English|
 */


data class CreditcardmerchantListElement (

    /* The unique ID of the Creditcardmerchant */
    @Json(name = "pkiCreditcardmerchantID")
    val pkiCreditcardmerchantID: kotlin.Int,

    /* The unique ID of the Bankaccount */
    @Json(name = "fkiBankaccountID")
    val fkiBankaccountID: kotlin.Int,

    /* Whether if visa are denied */
    @Json(name = "bCreditcardmerchantDenyvisa")
    val bCreditcardmerchantDenyvisa: kotlin.Boolean,

    /* Whether if mastercard are denied */
    @Json(name = "bCreditcardmerchantDenymastercard")
    val bCreditcardmerchantDenymastercard: kotlin.Boolean,

    /* Whether if amex are denied */
    @Json(name = "bCreditcardmerchantDenyamex")
    val bCreditcardmerchantDenyamex: kotlin.Boolean,

    /* Whether the creditcardmerchant is active or not */
    @Json(name = "bCreditcardmerchantIsactive")
    val bCreditcardmerchantIsactive: kotlin.Boolean,

    /* The description of the Creditcardmerchant */
    @Json(name = "sCreditcardmerchantDescription")
    val sCreditcardmerchantDescription: kotlin.String,

    /* The storeid of the Creditcardmerchant */
    @Json(name = "sCreditcardmerchantStoreid")
    val sCreditcardmerchantStoreid: kotlin.String,

    /* The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English| */
    @Json(name = "fkiLanguageID")
    val fkiLanguageID: kotlin.Int? = null

) {


}

