/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A Domain Object and children
 *
 * @param sDomainName The name of the Domain
 * @param pkiDomainID The unique ID of the Domain
 */


data class DomainRequestCompound (

    /* The name of the Domain */
    @Json(name = "sDomainName")
    val sDomainName: kotlin.String,

    /* The unique ID of the Domain */
    @Json(name = "pkiDomainID")
    val pkiDomainID: kotlin.Int? = null

) {


}

