/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An Ezsigntemplateformfieldgroupsigner Object and children to create a complete structure
 *
 * @param fkiEzsigntemplatesignerID The unique ID of the Ezsigntemplatesigner
 * @param pkiEzsigntemplateformfieldgroupsignerID The unique ID of the Ezsigntemplateformfieldgroupsigner
 */


data class EzsigntemplateformfieldgroupsignerRequestCompound (

    /* The unique ID of the Ezsigntemplatesigner */
    @Json(name = "fkiEzsigntemplatesignerID")
    val fkiEzsigntemplatesignerID: kotlin.Int,

    /* The unique ID of the Ezsigntemplateformfieldgroupsigner */
    @Json(name = "pkiEzsigntemplateformfieldgroupsignerID")
    val pkiEzsigntemplateformfieldgroupsignerID: kotlin.Int? = null

)

