/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An Ezsignsignergroup Object
 *
 * @param pkiEzsignsignergroupID The unique ID of the Ezsignsignergroup
 */


data class EzsignsignergroupMinusResponse (

    /* The unique ID of the Ezsignsignergroup */
    @Json(name = "pkiEzsignsignergroupID")
    val pkiEzsignsignergroupID: kotlin.Int

)

