/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import eZmaxApi.models.EzsigntemplatedocumentMinusEditEzsigntemplatesignaturesMinusV1MinusResponseMinusMPayload

import com.squareup.moshi.Json

/**
 * 
 *
 * @param mPayload 
 */


data class EzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseAllOf (

    @Json(name = "mPayload")
    val mPayload: EzsigntemplatedocumentMinusEditEzsigntemplatesignaturesMinusV1MinusResponseMinusMPayload

)

