/**
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.12
 * Contact: support-api@ezmax.ca
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import eZmaxApi.models.EzsigntemplatepackagemembershipMinusRequest

import com.squareup.moshi.Json

/**
 * A Ezsigntemplatepackagemembership Object and children
 *
 * @param fkiEzsigntemplatepackageID The unique ID of the Ezsigntemplatepackage
 * @param fkiEzsigntemplateID The unique ID of the Ezsigntemplate
 * @param pkiEzsigntemplatepackagemembershipID The unique ID of the Ezsigntemplatepackagemembership
 */

data class EzsigntemplatepackagemembershipMinusRequestCompound (

    /* The unique ID of the Ezsigntemplatepackage */
    @Json(name = "fkiEzsigntemplatepackageID")
    val fkiEzsigntemplatepackageID: kotlin.Int,

    /* The unique ID of the Ezsigntemplate */
    @Json(name = "fkiEzsigntemplateID")
    val fkiEzsigntemplateID: kotlin.Int,

    /* The unique ID of the Ezsigntemplatepackagemembership */
    @Json(name = "pkiEzsigntemplatepackagemembershipID")
    val pkiEzsigntemplatepackagemembershipID: kotlin.Int? = null

)

