/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Request for POST /1/object/ezsigntemplate/{pkiEzsigntemplateID}/copy
 *
 * @param aFkiEzsignfoldertypeID 
 */


data class EzsigntemplateCopyV1Request (

    @Json(name = "a_fkiEzsignfoldertypeID")
    val aFkiEzsignfoldertypeID: kotlin.collections.List<kotlin.Int>

)

