/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Response for PUT /1/object/ezsignsignergroup/{pkiEzsignsignergroupID}/editEzsignsignergroupmemberships
 *
 * @param aPkiEzsignsignergroupmembershipID 
 */


data class EzsignsignergroupEditEzsignsignergroupmembershipsV1ResponseMPayload (

    @Json(name = "a_pkiEzsignsignergroupmembershipID")
    val aPkiEzsignsignergroupmembershipID: kotlin.collections.List<kotlin.Int>

)

