/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import eZmaxApi.models.EzsignsignatureMinusGetObjectMinusV2MinusResponseMinusMPayload

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param mPayload 
 */


data class EzsignsignatureGetObjectV2ResponseAllOf (

    @Json(name = "mPayload")
    val mPayload: EzsignsignatureMinusGetObjectMinusV2MinusResponseMinusMPayload

)

