/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package eZmaxApi.models

import eZmaxApi.models.FieldEInscriptiontempStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A Inscriptiontemp List Element
 *
 * @param pkiInscriptiontempID The unique ID of the Inscriptiontemp
 * @param eInscriptiontempStatus 
 * @param sInscriptiontempDescription The description of the Inscriptiontemp
 * @param bInscriptiontempIsactive Whether the inscriptiontemp is active or not
 * @param dtCreatedDate The date and time at which the object was created
 * @param dtModifiedDate The date and time at which the object was last modified
 * @param sInscriptiontempMLS The mls of the Inscriptiontemp
 */


data class InscriptiontempListElement (

    /* The unique ID of the Inscriptiontemp */
    @Json(name = "pkiInscriptiontempID")
    val pkiInscriptiontempID: kotlin.Int,

    @Json(name = "eInscriptiontempStatus")
    val eInscriptiontempStatus: FieldEInscriptiontempStatus,

    /* The description of the Inscriptiontemp */
    @Json(name = "sInscriptiontempDescription")
    val sInscriptiontempDescription: kotlin.String,

    /* Whether the inscriptiontemp is active or not */
    @Json(name = "bInscriptiontempIsactive")
    val bInscriptiontempIsactive: kotlin.Boolean,

    /* The date and time at which the object was created */
    @Json(name = "dtCreatedDate")
    val dtCreatedDate: kotlin.String,

    /* The date and time at which the object was last modified */
    @Json(name = "dtModifiedDate")
    val dtModifiedDate: kotlin.String,

    /* The mls of the Inscriptiontemp */
    @Json(name = "sInscriptiontempMLS")
    val sInscriptiontempMLS: kotlin.String? = null

) {


}

