/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A Module AutocompleteElement Response
 *
 * @param pkiModuleID The unique ID of the Module
 * @param sModuleNameX The Name of the Module in the language of the requester
 * @param bModuleIsactive Whether the Module is active or not
 */


data class ModuleAutocompleteElementResponse (

    /* The unique ID of the Module */
    @Json(name = "pkiModuleID")
    val pkiModuleID: kotlin.Int,

    /* The Name of the Module in the language of the requester */
    @Json(name = "sModuleNameX")
    val sModuleNameX: kotlin.String,

    /* Whether the Module is active or not */
    @Json(name = "bModuleIsactive")
    val bModuleIsactive: kotlin.Boolean

)

