/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import eZmaxApi.models.CustomNotificationtestgetelementsResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Payload for GET /2/object/notificationtest/{pkiNotificationtestID}/getElements
 *
 * @param objNotificationtest 
 */


data class NotificationtestGetElementsV2ResponseMPayload (

    @Json(name = "objNotificationtest")
    val objNotificationtest: CustomNotificationtestgetelementsResponse

) {


}

