/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import eZmaxApi.models.RealestateassociationAutocompleteElementResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Payload for POST /2/object/realestateassociation/getAutocomplete
 *
 * @param aObjRealestateassociation An array of Realestateassociation autocomplete element response.
 */


data class RealestateassociationGetAutocompleteV2ResponseMPayload (

    /* An array of Realestateassociation autocomplete element response. */
    @Json(name = "a_objRealestateassociation")
    val aObjRealestateassociation: kotlin.collections.List<RealestateassociationAutocompleteElementResponse>

) {


}

