/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import eZmaxApi.models.VariableexpenseRequestCompound

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Request for POST /1/object/variableexpense
 *
 * @param aObjVariableexpense 
 */


data class VariableexpenseCreateObjectV1Request (

    @Json(name = "a_objVariableexpense")
    val aObjVariableexpense: kotlin.collections.List<VariableexpenseRequestCompound>

) {


}

