/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eZmaxApi.models

import eZmaxApi.models.FieldEVersionhistoryType
import eZmaxApi.models.FieldEVersionhistoryUsertype
import eZmaxApi.models.MultilingualVersionhistoryDetail
import eZmaxApi.models.VersionhistoryResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A Versionhistory Object
 *
 * @param pkiVersionhistoryID The unique ID of the Versionhistory
 * @param objVersionhistoryDetail 
 * @param dtVersionhistoryDate The date  at which the Versionhistory was published or should be published
 * @param eVersionhistoryType 
 * @param bVersionhistoryDraft Whether the Versionhistory is published or still a draft
 * @param fkiModuleID The unique ID of the Module
 * @param fkiModulesectionID The unique ID of the Modulesection
 * @param sModuleNameX The Name of the Module in the language of the requester
 * @param sModulesectionNameX The Name of the Modulesection in the language of the requester
 * @param eVersionhistoryUsertype 
 * @param dtVersionhistoryDateend The date  at which the Versionhistory will no longer be visible
 */


class VersionhistoryResponseCompound (

    /* The unique ID of the Versionhistory */
    @Json(name = "pkiVersionhistoryID")
    override val pkiVersionhistoryID: kotlin.Int,

    @Json(name = "objVersionhistoryDetail")
    override val objVersionhistoryDetail: MultilingualVersionhistoryDetail,

    /* The date  at which the Versionhistory was published or should be published */
    @Json(name = "dtVersionhistoryDate")
    override val dtVersionhistoryDate: kotlin.String,

    @Json(name = "eVersionhistoryType")
    override val eVersionhistoryType: FieldEVersionhistoryType,

    /* Whether the Versionhistory is published or still a draft */
    @Json(name = "bVersionhistoryDraft")
    override val bVersionhistoryDraft: kotlin.Boolean,

    /* The unique ID of the Module */
    @Json(name = "fkiModuleID")
    override val fkiModuleID: kotlin.Int? = null,

    /* The unique ID of the Modulesection */
    @Json(name = "fkiModulesectionID")
    override val fkiModulesectionID: kotlin.Int? = null,

    /* The Name of the Module in the language of the requester */
    @Json(name = "sModuleNameX")
    override val sModuleNameX: kotlin.String? = null,

    /* The Name of the Modulesection in the language of the requester */
    @Json(name = "sModulesectionNameX")
    override val sModulesectionNameX: kotlin.String? = null,

    @Json(name = "eVersionhistoryUsertype")
    override val eVersionhistoryUsertype: FieldEVersionhistoryUsertype? = null,

    /* The date  at which the Versionhistory will no longer be visible */
    @Json(name = "dtVersionhistoryDateend")
    override val dtVersionhistoryDateend: kotlin.String? = null

) : VersionhistoryResponse {


}

