/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package eZmaxApi.models

import eZmaxApi.models.AttemptResponseCompound
import eZmaxApi.models.CustomEzmaxpartnerproductSubscribe
import eZmaxApi.models.CustomWebhookResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * This is the base Webhook object
 *
 * @param objWebhook 
 * @param aObjAttempt An array containing details of previous attempts that were made to deliver the message. The array is empty if it's the first attempt.
 * @param objEzmaxpartnerproduct 
 * @param sExternalID 
 * @param sApikeyApikey 
 * @param sApikeySecret 
 */


data class WebhookEzmaxpartnerproductSubscribe (

    @Json(name = "objWebhook")
    val objWebhook: CustomWebhookResponse,

    /* An array containing details of previous attempts that were made to deliver the message. The array is empty if it's the first attempt. */
    @Json(name = "a_objAttempt")
    val aObjAttempt: kotlin.collections.List<AttemptResponseCompound>,

    @Json(name = "objEzmaxpartnerproduct")
    val objEzmaxpartnerproduct: CustomEzmaxpartnerproductSubscribe,

    @Json(name = "sExternalID")
    val sExternalID: kotlin.String? = null,

    @Json(name = "sApikeyApikey")
    val sApikeyApikey: kotlin.String? = null,

    @Json(name = "sApikeySecret")
    val sApikeySecret: kotlin.String? = null

) {


}

